// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered crop recommendations tailored to the user's location and current conditions.
 *
 * @function generateCropRecommendation - The main function to generate crop recommendations.
 * @typedef {Object} GenerateCropRecommendationInput - The input type for the generateCropRecommendation function.
 * @typedef {Object} GenerateCropRecommendationOutput - The return type for the generateCropRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCropRecommendationInputSchema = z.object({
  location: z.string().describe('The geographical location of the farm.'),
  soilType: z.string().describe('The type of soil on the farm.'),
  weatherConditions: z.string().describe('The current weather conditions at the farm.'),
  growingExperience: z.string().describe('The experience level of the farmer'),
  preferences: z.string().describe('The farmers preferences for the type of crop.'),
});

export type GenerateCropRecommendationInput = z.infer<typeof GenerateCropRecommendationInputSchema>;

const GenerateCropRecommendationOutputSchema = z.object({
  cropRecommendation: z.string().describe('The AI-powered crop recommendation.'),
  reasoning: z.string().describe('The reasoning behind the crop recommendation.'),
});

export type GenerateCropRecommendationOutput = z.infer<typeof GenerateCropRecommendationOutputSchema>;

export async function generateCropRecommendation(input: GenerateCropRecommendationInput): Promise<GenerateCropRecommendationOutput> {
  return generateCropRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCropRecommendationPrompt',
  input: {
    schema: GenerateCropRecommendationInputSchema,
  },
  output: {
    schema: GenerateCropRecommendationOutputSchema,
  },
  prompt: `You are an expert agricultural advisor providing crop recommendations to farmers.

  Based on the following information, provide a crop recommendation and explain your reasoning.

  Location: {{{location}}}
  Soil Type: {{{soilType}}}
  Weather Conditions: {{{weatherConditions}}}
  Farmer Experience: {{{growingExperience}}}
  Farmer Preferences: {{{preferences}}}

  Consider local climate, soil suitability, market demand, and the farmer's experience level when making your recommendation.
  Format your response as follows:

  Crop Recommendation: [Recommended Crop]
  Reasoning: [Explanation of why this crop is recommended]`, 
});

const generateCropRecommendationFlow = ai.defineFlow(
  {
    name: 'generateCropRecommendationFlow',
    inputSchema: GenerateCropRecommendationInputSchema,
    outputSchema: GenerateCropRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
